version: '3.8'

services:
  mcp-server-asana:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ASANA_ACCESS_TOKEN=${ASANA_ACCESS_TOKEN}
    restart: unless-stopped